defaults: &defaults
  host: 67.202.50.113
  port: 27017

development:
  <<: *defaults
  database: emailitfaggot_development

test:
  <<: *defaults
  database: emailitfaggot_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: emailitfaggot
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
